server:
  port: ${SERVER_PORT:9999}

app:
  worker:
    pool-size: 15
  client:
    web:
      connection-timeout: 5000
      max-connections: ${CLIENT_MAX_CONNECTIONS:200}
    processor:
      defalt-payment: ${URL_PROCESSOR_DEFAULT_PAYMENT:http://localhost:8001/payments}
      fallback-payment: ${URL_PROCESSOR_FALLBACK_PAYMENT:http://localhost:8002/payments}
      max-retries: 5

spring:
  application:
    name: api

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rinha}
    username: ${DB_USER:rinha}
    password: ${DB_PASS:rinha}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  loggin:
    level:
      root: off
      br.com.wlsc.api: ${APP_LOG_LEVEL:INFO}